# cmake/embed_font.cmake — convert a binary file (TTF) into a C header
# defining a uint8_t array + a size constant.
#
# Inputs (set on the cmake command line via -D…):
#   TTF_INPUT      path to the binary file
#   HEADER_OUTPUT  path to the .h to write
#
# Generates:
#   const unsigned char kFontAudioTTF[] = { 0x00, 0x01, … };
#   constexpr size_t   kFontAudioTTFSize = N;

if(NOT TTF_INPUT OR NOT HEADER_OUTPUT)
    message(FATAL_ERROR "embed_font.cmake: TTF_INPUT and HEADER_OUTPUT must be set")
endif()

file(READ "${TTF_INPUT}" CONTENT HEX)
string(LENGTH "${CONTENT}" HEX_LEN)
math(EXPR BYTE_LEN "${HEX_LEN} / 2")

# Insert ", 0x" between every pair of hex digits, then trim the leading ", "
string(REGEX REPLACE "(..)" ", 0x\\1" CONTENT "${CONTENT}")
string(SUBSTRING "${CONTENT}" 2 -1 CONTENT)

file(WRITE "${HEADER_OUTPUT}"
"// Auto-generated by cmake/embed_font.cmake from ${TTF_INPUT}
// Do not edit — regenerate by reconfiguring CMake.
#pragma once
#include <cstddef>

namespace mmp {
inline constexpr unsigned char kFontAudioTTF[] = {
    ${CONTENT}
};
inline constexpr std::size_t kFontAudioTTFSize = ${BYTE_LEN};
} // namespace mmp
")
