# cmake/embed_svgs.cmake — recursively reads every .svg under SVG_DIR
# and writes a header that exposes:
#
#   1. A `name` sub-namespace of `inline constexpr const char*` constants,
#      one per file. Lightweight — IconAudio.h pulls this so callers can
#      autocomplete every shipped glyph.
#
#   2. (gated by `#define MMP_INCLUDE_SVG_TABLES`) A `kTable[]` with the
#      raw SVG bytes via C++ raw-string literals, used by IconAudio.cpp's
#      lookup. Heavy — only the icon implementation includes the data.
#
# Inputs (-D…):
#   SVG_DIR        directory rooted at the SVG tree
#   NAMESPACE      identifier under mmp::svg:: to put the table in
#   HEADER_OUTPUT  path to the generated .h
#
# Identifier rule for `name::*` constants: split each filename on
# `[/-]`, capitalise each token, join. Files with leading digits are
# prefixed with `_` so they remain valid C++ identifiers. The string
# value of every constant is the path-relative-to-SVG_DIR with the
# trailing ".svg" stripped — exactly the lookup key used by iconAudio().

if(NOT SVG_DIR OR NOT NAMESPACE OR NOT HEADER_OUTPUT)
    message(FATAL_ERROR
            "embed_svgs.cmake: SVG_DIR, NAMESPACE, HEADER_OUTPUT all required")
endif()

# Capitalise the first character of `s`.
function(_capitalize out s)
    string(SUBSTRING "${s}" 0 1 head)
    string(TOUPPER "${head}" head)
    string(SUBSTRING "${s}" 1 -1 tail)
    set("${out}" "${head}${tail}" PARENT_SCOPE)
endfunction()

# Convert a key like "fad-armrecording" or "DeepinOpenSymbol/airplane"
# into a camel-case C++ identifier ("FadArmrecording", "DeepinOpenSymbolAirplane").
function(_to_identifier out key)
    string(REGEX REPLACE "[/_-]" ";" parts "${key}")
    set(camel "")
    foreach(p IN LISTS parts)
        if(NOT "${p}" STREQUAL "")
            _capitalize(p "${p}")
            set(camel "${camel}${p}")
        endif()
    endforeach()
    if(camel MATCHES "^[0-9]")
        set(camel "_${camel}")
    endif()
    set("${out}" "${camel}" PARENT_SCOPE)
endfunction()

file(GLOB_RECURSE SVG_FILES "${SVG_DIR}/*.svg")
list(SORT SVG_FILES)

set(NAMES_BODY "")
set(TABLE_BODY "")
foreach(f IN LISTS SVG_FILES)
    file(RELATIVE_PATH rel "${SVG_DIR}" "${f}")
    # Skip dotfiles (e.g. .notdef_*.svg / .null_*.svg from OpenSymbol)
    # — they're not real glyphs and their leading "." breaks C++ identifiers.
    get_filename_component(base "${rel}" NAME)
    if(base MATCHES "^\\.")
        continue()
    endif()
    string(REGEX REPLACE "\\.svg$" "" key "${rel}")
    _to_identifier(ident "${key}")
    file(READ "${f}" content)
    string(APPEND NAMES_BODY
        "    inline constexpr const char* ${ident} = \"${key}\";\n")
    string(APPEND TABLE_BODY
        "    { name::${ident}, R\"_SVG_(${content})_SVG_\" },\n")
endforeach()

list(LENGTH SVG_FILES SVG_COUNT)
message(STATUS "embed_svgs: ${NAMESPACE}: ${SVG_COUNT} svgs -> ${HEADER_OUTPUT}")

file(WRITE "${HEADER_OUTPUT}"
"// Auto-generated by cmake/embed_svgs.cmake. Do not edit.
#pragma once
#include <cstddef>

namespace mmp { namespace svg { namespace ${NAMESPACE} {

// Lookup-key constants for every embedded glyph. Pass these to
// mmp::iconAudio(...). Lightweight — included by IconAudio.h.
namespace name {
${NAMES_BODY}} // namespace name

#ifdef MMP_INCLUDE_SVG_TABLES
struct Entry { const char* name; const char* data; };

inline constexpr Entry kTable[] = {
${TABLE_BODY}};

inline constexpr std::size_t kTableSize = sizeof(kTable)/sizeof(Entry);
#endif

}}} // namespace mmp::svg::${NAMESPACE}
")
